// Accent colors and every neutral/text/border/background color in the
// `styles` object below are CSS custom properties, not literal hex values,
// so the whole app re-themes just by swapping which :root[data-theme=...]
// block is active (see THEME_CSS / applyTheme in skupni-koledar.jsx) -- no
// per-render style recomputation needed.
export const GREEN = "var(--green)";
export const GREEN_BG = "var(--green-bg)";
export const ORANGE = "var(--orange)";
export const RED = "var(--red)";
export const RED_BG = "var(--red-bg)";
export const PINK = "var(--pink)";
export const NEUTRAL_BG = "var(--divider)";
export const NEUTRAL_TEXT = "var(--neutral-text)";

export const styles = {
  page: {
    minHeight: "100vh",
    background: "var(--bg)",
    fontFamily:
      "'Rubik', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
    color: "var(--text)",
    paddingBottom: 40,
  },
  centerScreen: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "var(--bg)",
    fontFamily:
      "'Rubik', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
    padding: 20,
  },
  loadingDot: {
    width: 10,
    height: 10,
    borderRadius: "50%",
    background: GREEN,
  },
  introCard: {
    width: "100%",
    maxWidth: 360,
    background: "var(--card-bg)",
    borderRadius: 20,
    padding: "32px 28px",
    boxShadow: "0 1px 3px rgba(35,48,41,0.08), 0 8px 24px rgba(35,48,41,0.06)",
    border: "1px solid var(--border)",
  },
  introEyebrow: {
    fontSize: 11,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    fontWeight: 700,
    marginBottom: 8,
  },
  introTitle: {
    fontSize: 26,
    fontWeight: 800,
    margin: "0 0 8px 0",
    color: "var(--text-heading)",
  },
  introText: {
    fontSize: 14.5,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
    margin: "0 0 22px 0",
  },
  input: {
    width: "100%",
    boxSizing: "border-box",
    padding: "13px 14px",
    fontSize: 16,
    borderRadius: 12,
    border: "1.5px solid var(--border-input)",
    outline: "none",
    marginBottom: 14,
    background: "var(--input-bg)",
    color: "var(--text)",
  },
  primaryButton: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: "13px 14px",
    fontSize: 15.5,
    fontWeight: 700,
    color: "#fff",
    background: GREEN,
    border: "none",
    borderRadius: 12,
    cursor: "pointer",
  },
  introSecondaryButton: {
    width: "100%",
    marginTop: 10,
    padding: "13px 14px",
    fontSize: 14.5,
    fontWeight: 600,
    color: "var(--text-secondary)",
    background: "transparent",
    border: "1.5px solid var(--border-input)",
    borderRadius: 12,
    cursor: "pointer",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    padding: "20px 20px 24px 20px",
  },
  eyebrow: {
    fontSize: 11,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    fontWeight: 700,
    marginBottom: 10,
  },
  headerTitle: {
    fontSize: 19,
    fontWeight: 500,
    margin: 0,
    color: "var(--text-heading)",
  },
  headerAccent: {
    color: GREEN,
    fontWeight: 700,
  },
  avatarButton: {
    position: "relative",
    width: 42,
    height: 42,
    borderRadius: "50%",
    background: GREEN_BG,
    color: GREEN,
    border: "1px solid var(--avatar-border)",
    fontWeight: 700,
    fontSize: 14,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  pencilBadge: {
    position: "absolute",
    bottom: -2,
    right: -2,
    background: "var(--bg)",
    borderRadius: "50%",
    padding: 2,
    color: "var(--text-secondary)",
  },
  editNameRow: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    padding: "0 20px 8px 20px",
  },
  clashRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 8,
    padding: "0 20px 8px 20px",
  },
  editNameInputs: {
    display: "flex",
    gap: 8,
  },
  editNameActions: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  editNameActionsLeft: {
    display: "flex",
    gap: 8,
  },
  inputSmall: {
    flex: 1,
    minWidth: 0,
    boxSizing: "border-box",
    padding: "9px 12px",
    fontSize: 14,
    borderRadius: 10,
    border: "1.5px solid var(--border-input)",
    outline: "none",
    background: "var(--input-bg)",
    color: "var(--text)",
  },
  smallButton: {
    padding: "9px 14px",
    fontSize: 13.5,
    fontWeight: 700,
    color: "#fff",
    background: GREEN,
    border: "none",
    borderRadius: 10,
    cursor: "pointer",
  },
  clashText: {
    flex: 1,
    alignSelf: "center",
    fontSize: 13,
    color: RED,
  },
  smallButtonGhost: {
    padding: "9px 14px",
    fontSize: 13.5,
    fontWeight: 600,
    color: "var(--text-secondary)",
    background: "transparent",
    border: "1.5px solid var(--border-input)",
    borderRadius: 10,
    cursor: "pointer",
  },
  smallButtonDanger: {
    padding: "9px 14px",
    fontSize: 13.5,
    fontWeight: 700,
    color: "#fff",
    background: RED,
    border: "none",
    borderRadius: 10,
    cursor: "pointer",
  },
  errorBanner: {
    margin: "0 20px 10px 20px",
    padding: "9px 12px",
    fontSize: 13,
    background: RED_BG,
    color: RED,
    borderRadius: 10,
  },
  errorBannerIntro: {
    padding: "9px 12px",
    fontSize: 12.5,
    background: RED_BG,
    color: RED,
    borderRadius: 10,
    marginBottom: 14,
  },
  legend: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    padding: "4px 20px 14px 20px",
  },
  recentEventsHeading: {
    fontSize: 12,
    fontWeight: 800,
    color: GREEN,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    padding: "0 20px",
    marginBottom: 10,
  },
  recentEventsViewport: {
    overflow: "hidden",
    padding: "0 15px 18px 15px",
  },
  recentEventsTrack: (extendedCount, offset, animate) => ({
    display: "flex",
    width: `${(extendedCount / 3) * 100}%`,
    transform: `translateX(-${offset * (100 / extendedCount)}%)`,
    transition: animate ? "transform 500ms ease" : "none",
  }),
  recentEventSlot: (percent) => ({
    flex: `0 0 ${percent}%`,
    minWidth: 0,
    boxSizing: "border-box",
    padding: "0 5px",
  }),
  recentEventCard: (hue) => ({
    aspectRatio: "1",
    width: "100%",
    minWidth: 0,
    boxSizing: "border-box",
    borderRadius: 14,
    padding: 10,
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    gap: 4,
    background: `rgba(${hue}, 0.16)`,
    border: `1px solid rgba(${hue}, 0.32)`,
    boxShadow: `0 8px 18px -9px rgba(${hue}, 0.28), 0 1px 4px rgba(20, 30, 25, 0.05)`,
    overflow: "hidden",
  }),
  // The card is a fixed square, so its vertical budget is fixed too. A card
  // that also shows a keyword has one more row to fit, and a title wrapping
  // to a second line is what pushes the keyword out; clamp it to one line
  // and ellipsize. Without a keyword there's room to spare, so a long name
  // is better wrapped over two lines than cut short.
  //
  // The two clamps use different mechanisms on purpose: -webkit-box is the
  // only way to ellipsize at a line *count*, but at one line it can't
  // ellipsize a single word longer than the card (it just clips), which
  // nowrap + text-overflow handles correctly.
  recentEventTitle: (singleLine) => ({
    fontSize: 14,
    fontWeight: 800,
    color: "var(--text-heading)",
    lineHeight: 1.2,
    marginBottom: 2,
    minWidth: 0,
    overflow: "hidden",
    ...(singleLine
      ? { textOverflow: "ellipsis", whiteSpace: "nowrap" }
      : {
          display: "-webkit-box",
          WebkitLineClamp: 2,
          WebkitBoxOrient: "vertical",
        }),
  }),
  recentEventDate: {
    fontSize: 11,
    fontWeight: 600,
    color: "var(--text-muted)",
  },
  recentEventTime: {
    fontSize: 16,
    fontWeight: 800,
    color: "var(--text-heading)",
  },
  recentEventKeyword: {
    fontSize: 11.5,
    fontWeight: 600,
    color: "var(--text-secondary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  syncLabel: {
    fontSize: 11.5,
    color: "var(--text-faint)",
    fontStyle: "italic",
  },
  list: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    padding: "0 16px",
  },
  dayCard: (isToday, isOpen) => ({
    background: "var(--card-bg)",
    borderRadius: 16,
    border:
      isOpen || isToday ? `1.5px solid ${GREEN}` : "1px solid var(--border)",
    boxShadow: isToday ? `0 0 0 3px ${GREEN_BG}` : "none",
    overflow: "hidden",
  }),
  dayHeader: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: "12px 14px",
    background: "transparent",
    border: "none",
    cursor: "pointer",
    textAlign: "left",
  },
  dayDateBlock: {
    width: 48,
    flexShrink: 0,
    textAlign: "center",
  },
  dayNum: {
    fontSize: 20,
    fontWeight: 800,
    color: "var(--text-heading)",
    lineHeight: 1.1,
  },
  dayName: {
    fontSize: 12.5,
    color: "var(--text-muted)",
    textTransform: "capitalize",
    fontWeight: 600,
  },
  dayPeople: {
    flex: 1,
    display: "flex",
    flexWrap: "wrap",
    gap: 5,
    alignItems: "center",
  },
  noOne: {
    fontSize: 12.5,
    color: "var(--text-fainter)",
    fontStyle: "italic",
  },
  emptyNote: {
    fontSize: 13,
    color: "var(--text-fainter)",
    fontStyle: "italic",
  },
  avatarChip: (color) => ({
    width: 26,
    height: 26,
    borderRadius: "50%",
    background: color,
    color: "#fff",
    fontSize: 10.5,
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  }),
  eventBadge: {
    height: 26,
    boxSizing: "border-box",
    padding: "0 9px",
    borderRadius: 13,
    background: PINK,
    color: "#fff",
    fontSize: 9.5,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.02em",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    whiteSpace: "nowrap",
  },
  dayDetail: {
    borderTop: "1px solid var(--divider)",
    padding: "14px",
  },
  gridHeaderRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  sectionLabel: {
    fontSize: 11.5,
    fontWeight: 700,
    color: "var(--text-muted)",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  },
  clearButton: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontSize: 11.5,
    fontWeight: 600,
    color: "var(--text-muted)",
    background: "transparent",
    border: "1px solid var(--border-input)",
    borderRadius: 7,
    padding: "4px 8px",
    cursor: "pointer",
  },
  headerButtonGroup: {
    display: "flex",
    gap: 6,
  },
  deleteButton: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontSize: 11.5,
    fontWeight: 600,
    color: RED,
    background: RED_BG,
    border: `1px solid ${RED}`,
    borderRadius: 7,
    padding: "4px 8px",
    cursor: "pointer",
  },
  modeRow: {
    display: "flex",
    gap: 8,
    marginBottom: 8,
  },
  pillButton: (active, color, bg) => ({
    flex: 1,
    padding: "9px 6px",
    fontSize: 13,
    fontWeight: 700,
    color: active ? "#fff" : color,
    background: active ? color : bg,
    border: `1.5px solid ${color}`,
    borderRadius: 9,
    cursor: "pointer",
  }),
  hint: {
    fontSize: 11.5,
    color: "var(--text-faint)",
    margin: "0 0 10px 0",
    lineHeight: 1.4,
  },
  addNoteButton: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    fontSize: 12.5,
    fontWeight: 600,
    color: GREEN,
    background: GREEN_BG,
    border: "none",
    borderRadius: 8,
    padding: "7px 10px",
    marginBottom: 14,
    cursor: "pointer",
  },
  noteBlock: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    marginBottom: 14,
  },
  noteTextarea: {
    width: "100%",
    boxSizing: "border-box",
    resize: "vertical",
    padding: "9px 11px",
    fontSize: 13.5,
    fontFamily: "inherit",
    borderRadius: 10,
    border: "1.5px solid var(--border-input)",
    outline: "none",
    background: "var(--input-bg)",
    color: "var(--text)",
  },
  noteRemoveButton: {
    alignSelf: "flex-start",
    fontSize: 11.5,
    fontWeight: 600,
    color: RED,
    background: "transparent",
    border: "none",
    padding: "2px 0",
    cursor: "pointer",
  },
  hourGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(6, 1fr)",
    gap: 6,
    marginBottom: 16,
    touchAction: "none",
    userSelect: "none",
  },
  hourCell: {
    aspectRatio: "1",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    fontSize: 12.5,
    fontWeight: 700,
    cursor: "pointer",
  },
  saveButton: (saved) => ({
    flex: 1,
    padding: "11px",
    fontSize: 13.5,
    fontWeight: 700,
    color: "#fff",
    background: saved ? GREEN : "var(--surface-strong)",
    border: "none",
    borderRadius: 10,
    cursor: "pointer",
    transition: "background 150ms ease",
  }),
  editActionsRow: {
    display: "flex",
    gap: 8,
    marginBottom: 4,
  },
  cancelButton: {
    flex: 1,
    padding: "11px",
    fontSize: 13.5,
    fontWeight: 700,
    color: "var(--text-secondary)",
    background: "transparent",
    border: "1.5px solid var(--border-input)",
    borderRadius: 10,
    cursor: "pointer",
  },
  savedFlash: {
    fontSize: 12.5,
    fontWeight: 700,
    color: GREEN,
    background: GREEN_BG,
    borderRadius: 8,
    padding: "7px 10px",
    marginBottom: 10,
    textAlign: "center",
  },
  emptyState: {
    textAlign: "center",
    padding: "14px 8px 6px 8px",
  },
  emptyStateText: {
    fontSize: 13.5,
    color: "var(--text-muted)",
    margin: "0 0 12px 0",
  },
  addButton: {
    padding: "11px 20px",
    fontSize: 13.5,
    fontWeight: 700,
    color: "#fff",
    background: "var(--surface-strong)",
    border: "none",
    borderRadius: 10,
    cursor: "pointer",
  },
  addButtonSecondary: {
    width: "100%",
    padding: "10px",
    marginTop: 6,
    fontSize: 13,
    fontWeight: 700,
    color: GREEN,
    background: GREEN_BG,
    border: "none",
    borderRadius: 9,
    cursor: "pointer",
  },
  peopleSection: {
    borderTop: "1px solid var(--divider)",
    paddingTop: 12,
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  addEventButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    padding: "7px 11px",
    marginTop: -12,
    marginBottom: 6,
    fontSize: 12.5,
    fontWeight: 700,
    color: GREEN,
    background: GREEN_BG,
    border: `1.5px dashed ${GREEN}`,
    borderRadius: 9,
    cursor: "pointer",
  },
  eventTimeRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginBottom: 14,
  },
  eventTimeSep: {
    fontSize: 13,
    fontWeight: 700,
    color: "var(--text-secondary)",
  },
  eventCard: {
    background: GREEN_BG,
    border: `1px solid ${GREEN}`,
    borderRadius: 14,
    padding: 14,
    marginBottom: 14,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  eventHeaderRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 8,
  },
  eventHeaderActions: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    flexShrink: 0,
  },
  eventEyebrow: {
    fontSize: 10.5,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    color: GREEN,
  },
  eventEyebrowMeta: {
    fontSize: 11.5,
    textTransform: "none",
    letterSpacing: "normal",
  },
  eventTitle: {
    fontSize: 15,
    fontWeight: 800,
    color: "var(--text-heading)",
    marginTop: 2,
  },
  eventDuration: {
    fontSize: 12,
    color: "var(--text-secondary)",
    marginTop: 2,
  },
  eventDescription: {
    fontSize: 13,
    color: "var(--text-strong)",
    lineHeight: 1.4,
    margin: 0,
  },
  attendButton: (active) => ({
    alignSelf: "flex-start",
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "8px 16px",
    fontSize: 13,
    fontWeight: 700,
    color: active ? "#fff" : GREEN,
    background: active ? GREEN : "var(--card-bg)",
    border: `1.5px solid ${GREEN}`,
    borderRadius: 9,
    cursor: "pointer",
  }),
  eventAttendees: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
  },
  entryRow: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    gap: 10,
    width: "100%",
    padding: "9px 4px",
    background: "transparent",
    border: "none",
    borderBottom: "1px solid var(--divider-soft)",
    cursor: "pointer",
    textAlign: "left",
  },
  entryRowWrap: {
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  editEntryButton: {
    flexShrink: 0,
    width: 30,
    height: 30,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: GREEN,
    background: GREEN_BG,
    border: "none",
    borderRadius: 8,
    cursor: "pointer",
    marginBottom: 1,
  },
  entryDot: {
    width: 9,
    height: 9,
    borderRadius: "50%",
    flexShrink: 0,
  },
  entryTextCol: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  entryName: {
    fontSize: 14,
    fontWeight: 600,
    color: "var(--text-strong)",
  },
  entryNoteText: {
    fontSize: 12,
    color: "var(--text-note)",
    fontStyle: "italic",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  entryYou: {
    fontSize: 12,
    fontWeight: 500,
    color: "var(--text-faint)",
  },
  entryQuickStatus: {
    fontSize: 12,
    fontWeight: 500,
    color: "var(--text-note)",
  },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(27,46,36,0.45)",
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
    zIndex: 50,
  },
  modalCard: {
    width: "100%",
    maxWidth: 420,
    background: "var(--card-bg)",
    borderRadius: "18px 18px 0 0",
    borderTop: `3px solid ${GREEN}`,
    padding: "18px 20px 26px 20px",
    maxHeight: "78vh",
    overflowY: "auto",
    boxSizing: "border-box",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 14,
  },
  modalEyebrow: {
    fontSize: 11,
    fontWeight: 700,
    color: "var(--text-muted)",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    marginBottom: 2,
  },
  modalTitle: {
    fontSize: 19,
    fontWeight: 800,
    color: "var(--text-heading)",
  },
  modalNote: {
    fontSize: 13,
    color: "var(--text-secondary)",
    fontStyle: "italic",
    marginTop: 4,
  },
  modalClose: {
    fontSize: 12.5,
    fontWeight: 700,
    color: "var(--text-secondary)",
    background: "var(--divider)",
    border: "none",
    borderRadius: 8,
    padding: "7px 12px",
    cursor: "pointer",
  },
  modalTable: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    marginBottom: 16,
  },
  modalRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "8px 10px",
    background: "var(--bg)",
    borderRadius: 9,
  },
  modalTime: {
    fontSize: 14,
    fontWeight: 700,
    color: "var(--text)",
  },
  modalBadge: {
    fontSize: 12,
    fontWeight: 700,
    padding: "4px 10px",
    borderRadius: 999,
  },
  modalStrip: {
    display: "flex",
    gap: 1,
    marginBottom: 4,
  },
  modalStripCell: {
    flex: 1,
    height: 16,
    borderRadius: 1.5,
  },
  modalStripLabels: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: 10.5,
    color: "var(--text-fainter)",
  },
  footer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginTop: 24,
    fontSize: 12,
    color: "var(--text-faint)",
  },
  settingsButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    margin: "16px auto 0 auto",
    padding: "9px 16px",
    fontSize: 12.5,
    fontWeight: 600,
    color: "var(--text-secondary)",
    background: "var(--card-bg)",
    border: "1px solid var(--border)",
    borderRadius: 10,
    cursor: "pointer",
  },
  appFooterNote: {
    margin: "20px auto 0 auto",
    maxWidth: 320,
    padding: "0 20px",
    fontSize: 11,
    lineHeight: 1.5,
    color: "var(--text-fainter)",
    textAlign: "center",
  },
  themeOptionButton: (active) => ({
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: "11px 6px",
    fontSize: 13.5,
    fontWeight: 700,
    color: active ? "#fff" : GREEN,
    background: active ? GREEN : GREEN_BG,
    border: `1.5px solid ${GREEN}`,
    borderRadius: 9,
    cursor: "pointer",
  }),
  pageDesktop: {
    minHeight: "100vh",
    background: "var(--bg)",
    fontFamily:
      "'Rubik', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
    color: "var(--text)",
    paddingBottom: 40,
  },
  desktopContainer: {
    maxWidth: 980,
    margin: "0 auto",
    padding: "0 8px",
  },
  desktopLayout: {
    display: "flex",
    gap: 20,
    alignItems: "flex-start",
    padding: "0 16px",
  },
  dayGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(7, minmax(0, 1fr))",
    gap: 6,
    width: 322,
    flexShrink: 0,
  },
  daySquare: (selected, isToday) => ({
    aspectRatio: "1",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    borderRadius: 9,
    border: selected || isToday ? `1.5px solid ${GREEN}` : "1px solid var(--border)",
    boxShadow: !selected && isToday ? `0 0 0 3px ${GREEN_BG}` : "none",
    background: selected ? GREEN_BG : "var(--card-bg)",
    cursor: "pointer",
    padding: 2,
  }),
  daySquareNum: {
    fontSize: 14.5,
    fontWeight: 800,
    color: "var(--text-heading)",
    lineHeight: 1.1,
  },
  daySquareLabel: {
    fontSize: 11,
    color: "var(--text-muted)",
    textTransform: "capitalize",
    fontWeight: 600,
  },
  daySquareDots: {
    display: "flex",
    gap: 3,
    marginTop: 2,
    height: 6,
  },
  miniDot: (color) => ({
    width: 6,
    height: 6,
    borderRadius: "50%",
    background: color,
    display: "inline-block",
  }),
  detailPanel: {
    flex: 1,
    background: "var(--card-bg)",
    borderRadius: 16,
    border: "1px solid var(--border)",
    padding: 20,
    minHeight: 380,
  },
  detailHeaderRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
    paddingBottom: 14,
    borderBottom: "1px solid var(--divider)",
  },
  detailDateNum: {
    fontSize: 24,
    fontWeight: 800,
    color: "var(--text-heading)",
    lineHeight: 1.1,
  },
  detailDateLabel: {
    fontSize: 12.5,
    color: "var(--text-muted)",
    textTransform: "capitalize",
    fontWeight: 600,
  },
  editEntryButtonLg: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 13,
    fontWeight: 700,
    color: GREEN,
    background: GREEN_BG,
    border: "none",
    borderRadius: 9,
    padding: "9px 14px",
    cursor: "pointer",
  },
  hourGridDesktop: {
    display: "grid",
    gridTemplateColumns: "repeat(12, 1fr)",
    gap: 5,
    marginBottom: 16,
    touchAction: "none",
    userSelect: "none",
  },
  hourCellDesktop: {
    aspectRatio: "1",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 7,
    fontSize: 11.5,
    fontWeight: 700,
    cursor: "pointer",
  },
};
